name: Code Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  coverage:
    name: Check code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov


      - name: Run coverage check
        run: |
          forge coverage --report lcov --no-match-coverage "(script|mocks)"
          
          # Check if coverage is above 90%
          COVERAGE=$(lcov --summary lcov.info | grep "lines" | cut -d ':' -f 2 | cut -d '%' -f 1 | xargs)
          echo "Current coverage: $COVERAGE%"
          
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "❌ Code coverage is below 90% threshold"
            echo "Required: 90%"
            echo "Current:  $COVERAGE%"
            exit 1
          fi
          echo "✅ Code coverage is above 90% threshold" 